BoxLayout:
    orientation: 'vertical'
    BoxLayout:
        id: dynamic_box
        orientation: 'vertical'
        cols: 1
        orientation: 'vertical'
    BoxLayout
        orientation: 'horizontal'
        size_hint_y: 0.2
        Button:
            text: 'Add labels'
            on_press: app.create_widgets()
        Button:
            text: 'Clear labels'
            on_press: app.clear_widgets()